apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus
  namespace: user1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/jduimovich0/devfile-sample-code-with-quarkus@sha256:08ef98ddfd1d0247fd89f7e7f6ab828e80f630115b4a8ccee8388afaefe71325
        name: my-java-quarkus
        resources: {}
status: {}
